FROM jenkins/inbound-agent:latest

USER root

RUN apt-get update && \
    apt-get install -y docker.io && \
    apt-get clean

ARG DOCKER_GID=983

RUN groupadd -g ${DOCKER_GID} docker || true
RUN usermod -aG docker jenkins

USER jenkins
